// lib/utils/product_data.dart
import '../models/product.dart';

List<Product> allProducts = [
  Product(
    id: '1',
    name: 'Chitato',
    category: 'Makanan',
    subCategory: 'Snack',
    emoji: '🍟',
    price: 10000,
    description: 'Keripik kentang rasa ayam panggang yang renyah dan gurih. Terbuat dari kentang pilihan, digoreng hingga renyah, dibumbui dengan rempah alami.',
    imageUrl: 'images/Chitato.jpg', // gunakan asset lokal
  ),
  Product(
    id: '2',
    name: 'Big Babol',
    category: 'Makanan',
    subCategory: 'Permen',
    emoji: '🍬',
    price: 2500,
    description: 'Permen susu rasa stroberi dengan tekstur kenyal. Mengandung susu asli dan ekstrak buah stroberi.',
    imageUrl: 'images/Bigbabol.jpg',
  ),
  Product(
    id: '3',
    name: 'Kacang Garuda',
    category: 'Makanan',
    subCategory: 'Snack',
    emoji: '🥜',
    price: 7000,
    description: 'Kacang tanah pilihan dengan kulit tipis, digoreng kering dan dibumbui bawang putih.',
    imageUrl: 'images/Kacang.jpg',
  ),
  Product(
    id: '4',
    name: 'Khong Guan',
    category: 'Makanan',
    subCategory: 'Biskuit',
    emoji: '🍪',
    price: 55000,
    description: 'Biskuit asin klasik dengan rasa gurih. Terbuat dari tepung terigu, margarin, dan sedikit gula.',
    imageUrl: 'images/Khongguan.jpg',
  ),
  Product(
    id: '5',
    name: 'Cocacola',
    category: 'Minuman',
    subCategory: 'Soda',
    emoji: '🥤',
    price: 6000,
    description: 'Minuman bersoda berkarbonasi dengan rasa khas.',
    imageUrl: 'images/Cocacola.jpg',
  ),
  Product(
    id: '6',
    name: 'Fanta',
    category: 'Minuman',
    subCategory: 'Soda',
    emoji: '🍊',
    price: 11000,
    description: 'Minuman rasa jeruk dengan soda. Tanpa kafein.',
    imageUrl: 'images/Fanta.jpg',
  ),
  Product(
    id: '7',
    name: 'Golda',
    category: 'Minuman',
    subCategory: 'Susu',
    emoji: '🥛',
    price: 5000,
    description: 'Susu kotak rasa cokelat dan stroberi. Terbuat dari susu sapi segar.',
    imageUrl: 'images/Golda.png',
  ),
  Product(
    id: '8',
    name: 'Le Minerale',
    category: 'Minuman',
    subCategory: 'Air Mineral',
    emoji: '💧',
    price: 8000,
    description: 'Air mineral alkali dengan pH alami.',
    imageUrl: 'images/Minerale.webp',
  ),
  Product(
    id: '9',
    name: 'Mylanta',
    category: 'Suplemen',
    subCategory: 'Obat Maag',
    emoji: '💊',
    price: 5000,
    description: 'Obat maag dengan kandungan aluminium hidroksida dan magnesium hidroksida.',
    imageUrl: 'images/Mylanta.jpg',
  ),
  Product(
    id: '10',
    name: 'OBH Combi',
    category: 'Suplemen',
    subCategory: 'Obat Batuk',
    emoji: '🌿',
    price: 18000,
    description: 'Obat batuk berdahak dan tidak berdahak. Sirup rasa jeruk.',
    imageUrl: 'images/Obhcombi.webp',
  ),
  Product(
    id: '11',
    name: 'Tolak Angin',
    category: 'Suplemen',
    subCategory: 'Herbal',
    emoji: '🌱',
    price: 2500,
    description: 'Herbal untuk masuk angin. Terdiri dari jahe, kencur, kayu manis, daun mint, dan madu.',
    imageUrl: 'images/Tolakangin.jpg',
  ),
  Product(
    id: '12',
    name: 'Oskadon',
    category: 'Suplemen',
    subCategory: 'Obat',
    emoji: '💊',
    price: 12500,
    description: 'Parasetamol 500 mg untuk meredakan demam, sakit kepala, dan nyeri otot.',
    imageUrl: 'images/Oskadon.jpg',
  ),
];